spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:8081/drones
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:changelogs/changelog.yaml

server:
  servlet:
    context-path: /api/v0.1