version: "3.9"
services:
  postgres:
    image: postgres:14.6-alpine
    environment:
      POSTGRES_DB: "drones"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "8081:5432"